name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # Устанавливаем Java 17 (требуется для последних версий Minecraft)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Даем права на выполнение Gradle wrapper
      - name: Grant execute permissions for Gradle
        run: |
          chmod +x gradlew
          chmod +r gradle/wrapper/gradle-wrapper.jar
          chmod -R 755 gradle/wrapper

      # Собираем проект с ShadowJar
      - name: Build with Gradle
        run: ./gradlew shadowJar

      # Выводим список собранных файлов
      - name: List build/libs
        run: ls -l build/libs

      # Загружаем собранный jar как артефакт
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/libs/*.jar
